- name: start logstash
  service:
    name: logstash
    state: started  

- name: restart logstash
  service: 
    name: logstash
    state: restarted
    enabled: yes

- name: stop logstash
  service:
    name: logstash
    state: stopped
  become: yes