- name: start elasticsearch
  service:
    name: elasticsearch
    state: started

- name: restart elasticsearch
  service: 
    name: elasticsearch
    state: restarted 
    enabled: yes

- name: stop elasticsearch
  service:
    name: elasticsearch
    state: stopped
  become: yes