---
- name: Install Kibana
  dnf: name=kibana state=present

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: "{{ kibana_ip }}"'

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.hosts:'
   line: 'elasticsearch.hosts: ["http://localhost:{{ elasticsearch_port }}"]'

- firewalld:
    port: 5601/tcp
    permanent: yes
    state: enabled

- name: start kibana
  service:
    name: kibana
    state: started