---
- name: Install Filebeat
  dnf: name=filebeat state=present

- name: Copy filebeat.yml file
  template: src=filebeat.yml dest=/etc/filebeat/filebeat.yml

- name: Copy system module config
  template: src=system.yml dest=/etc/filebeat/modules.d/system.yml

- name: Filebeat system module
  shell: filebeat modules enable system
  notify: start filebeat

- name: Install Metricbeat
  dnf: name=metricbeat state=present
  notify: start metricbeat