Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "centos/8"
    master.vm.hostname = "master"
    master.vm.network :forwarded_port, guest: 80, host: 4567
    master.vm.network "private_network", ip: "192.168.50.50"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end
