---
- name: Install MariaDB packages
  yum:
    name:
      - mariadb-server
      - MySQL-python
      - libselinux-python
      - libsemanage-python
    state: present

- name: Configure SELinux to start mysql
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes