- name: start kibana
  service:
    name: kibana
    state: started

- name: restart kibana
  service: 
    name: kibana
    state: restarted 
    enabled: yes

- name: stop kibana
  service:
    name: kibana
    state: stopped
  become: yes