---
- name: Install nginx
  dnf: name=nginx state=present

- name: Start nginx
  service: name=nginx state=started enabled=yes

- name: Copy nginx configuration for wordpress
  template: src=nextcloud.conf dest=/etc/nginx/conf.d/nextcloud.conf
  notify: restart nginx